
// This file has been generated by the GUI designer. Do not modify.

public partial class GUI
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action DateiAction;
	private global::Gtk.Action BearbeitenAction;
	private global::Gtk.Action BeendenAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.Notebook notebook2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Label label2;
	private global::Gtk.Entry zdezahl;
	private global::Gtk.ComboBox zdcbchosefrom;
	private global::Gtk.ComboBox zdcbchoseto;
	private global::Gtk.Button zdbconvert;
	private global::Gtk.HSeparator hseparator3;
	private global::Gtk.Label label3;
	private global::Gtk.Entry zdedarstellung;
	private global::Gtk.HBox hbox2;
	private global::Gtk.RadioButton zdrbfrom;
	private global::Gtk.RadioButton zdrbto;
	private global::Gtk.ComboBox zdcbdarstellung;
	private global::Gtk.Button zdbdarstellung;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Label label5;
	private global::Gtk.Entry zdeexzess;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label6;
	private global::Gtk.Entry zdebias;
	private global::Gtk.HBox hbox3;
	private global::Gtk.RadioButton zdrbexfrom;
	private global::Gtk.RadioButton zdrbexto;
	private global::Gtk.Button rdbexzess;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview1;
	private global::Gtk.Label label4;
	private global::Gtk.Label label1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label8;
	private global::Gtk.Entry GKZ1E;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label9;
	private global::Gtk.Entry GKZ2E;
	private global::Gtk.ComboBoxEntry GKZCB;
	private global::Gtk.HBox hbox5;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox6;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Label label10;
	private global::Gtk.Entry GKZ1Evz;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Label label11;
	private global::Gtk.Entry GKZ1Eex;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label label12;
	private global::Gtk.Entry GKZ1Eman;
	private global::Gtk.Label GtkLabel9;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.VBox vbox7;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Label label13;
	private global::Gtk.Entry GKZ2Evz;
	private global::Gtk.HBox hbox12;
	private global::Gtk.Label label14;
	private global::Gtk.Entry GKZ2Eex;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Label label15;
	private global::Gtk.Entry GKZ2Eman;
	private global::Gtk.Label GtkLabel10;
	private global::Gtk.VBox vbox8;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.Entry GKZEerg;
	private global::Gtk.Label GtkLabel12;
	private global::Gtk.Button GKZB;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView GKZTV;
	private global::Gtk.Label label7;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget GUI
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.DateiAction = new global::Gtk.Action ("DateiAction", global::Mono.Unix.Catalog.GetString ("Datei"), null, null);
		this.DateiAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Datei");
		w1.Add (this.DateiAction, null);
		this.BearbeitenAction = new global::Gtk.Action ("BearbeitenAction", global::Mono.Unix.Catalog.GetString ("Bearbeiten"), null, null);
		this.BearbeitenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Bearbeiten");
		w1.Add (this.BearbeitenAction, null);
		this.BeendenAction = new global::Gtk.Action ("BeendenAction", global::Mono.Unix.Catalog.GetString ("Beenden"), null, null);
		this.BeendenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Beenden");
		w1.Add (this.BeendenAction, "<Primary><Mod2>q");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "GUI";
		this.Title = global::Mono.Unix.Catalog.GetString ("KateDev's RS");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child GUI.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='DateiAction' action='DateiAction'><menuitem name='BeendenAction' action='BeendenAction'/></menu><menu name='BearbeitenAction' action='BearbeitenAction'/></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanDefault = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 2;
		this.notebook2.TabPos = ((global::Gtk.PositionType)(0));
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Umrechnung");
		this.vbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.zdezahl = new global::Gtk.Entry ();
		this.zdezahl.TooltipMarkup = "Zahl|Basis:Ziel-Basis";
		this.zdezahl.CanFocus = true;
		this.zdezahl.Name = "zdezahl";
		this.zdezahl.IsEditable = true;
		this.zdezahl.InvisibleChar = '•';
		this.vbox4.Add (this.zdezahl);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.zdezahl]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.zdcbchosefrom = global::Gtk.ComboBox.NewText ();
		this.zdcbchosefrom.AppendText (global::Mono.Unix.Catalog.GetString ("Binär"));
		this.zdcbchosefrom.AppendText (global::Mono.Unix.Catalog.GetString ("Dezimal"));
		this.zdcbchosefrom.AppendText (global::Mono.Unix.Catalog.GetString ("Hexadezimal"));
		this.zdcbchosefrom.AppendText ("");
		this.zdcbchosefrom.Name = "zdcbchosefrom";
		this.zdcbchosefrom.Active = 0;
		this.vbox4.Add (this.zdcbchosefrom);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.zdcbchosefrom]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.zdcbchoseto = global::Gtk.ComboBox.NewText ();
		this.zdcbchoseto.AppendText (global::Mono.Unix.Catalog.GetString ("Binär"));
		this.zdcbchoseto.AppendText (global::Mono.Unix.Catalog.GetString ("Dezimal"));
		this.zdcbchoseto.AppendText (global::Mono.Unix.Catalog.GetString ("Hexadezimal"));
		this.zdcbchoseto.AppendText ("");
		this.zdcbchoseto.Name = "zdcbchoseto";
		this.zdcbchoseto.Active = 1;
		this.vbox4.Add (this.zdcbchoseto);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.zdcbchoseto]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.zdbconvert = new global::Gtk.Button ();
		this.zdbconvert.CanFocus = true;
		this.zdbconvert.Events = ((global::Gdk.EventMask)(256));
		this.zdbconvert.Name = "zdbconvert";
		this.zdbconvert.UseUnderline = true;
		this.zdbconvert.Label = global::Mono.Unix.Catalog.GetString ("Convert...");
		this.vbox4.Add (this.zdbconvert);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.zdbconvert]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox4.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator3]));
		w8.Position = 5;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Darstellungsarten");
		this.vbox4.Add (this.label3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label3]));
		w9.Position = 6;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.zdedarstellung = new global::Gtk.Entry ();
		this.zdedarstellung.CanFocus = true;
		this.zdedarstellung.Name = "zdedarstellung";
		this.zdedarstellung.IsEditable = true;
		this.zdedarstellung.InvisibleChar = '•';
		this.vbox4.Add (this.zdedarstellung);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.zdedarstellung]));
		w10.Position = 7;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.zdrbfrom = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("From"));
		this.zdrbfrom.CanFocus = true;
		this.zdrbfrom.Name = "zdrbfrom";
		this.zdrbfrom.DrawIndicator = true;
		this.zdrbfrom.UseUnderline = true;
		this.zdrbfrom.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox2.Add (this.zdrbfrom);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.zdrbfrom]));
		w11.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.zdrbto = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("To"));
		this.zdrbto.CanFocus = true;
		this.zdrbto.Name = "zdrbto";
		this.zdrbto.DrawIndicator = true;
		this.zdrbto.UseUnderline = true;
		this.zdrbto.Group = this.zdrbfrom.Group;
		this.hbox2.Add (this.zdrbto);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.zdrbto]));
		w12.Position = 1;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w13.Position = 8;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.zdcbdarstellung = global::Gtk.ComboBox.NewText ();
		this.zdcbdarstellung.AppendText (global::Mono.Unix.Catalog.GetString ("Betrag"));
		this.zdcbdarstellung.AppendText (global::Mono.Unix.Catalog.GetString ("Festkomma-Betragszahl"));
		this.zdcbdarstellung.AppendText (global::Mono.Unix.Catalog.GetString ("Vorzeichen-Betrag"));
		this.zdcbdarstellung.AppendText (global::Mono.Unix.Catalog.GetString ("1er-komplement"));
		this.zdcbdarstellung.AppendText (global::Mono.Unix.Catalog.GetString ("2er-Komplement"));
		this.zdcbdarstellung.Name = "zdcbdarstellung";
		this.zdcbdarstellung.Active = 0;
		this.vbox4.Add (this.zdcbdarstellung);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.zdcbdarstellung]));
		w14.Position = 9;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.zdbdarstellung = new global::Gtk.Button ();
		this.zdbdarstellung.CanFocus = true;
		this.zdbdarstellung.Name = "zdbdarstellung";
		this.zdbdarstellung.UseUnderline = true;
		this.zdbdarstellung.Label = global::Mono.Unix.Catalog.GetString ("Convert...");
		this.vbox4.Add (this.zdbdarstellung);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.zdbdarstellung]));
		w15.Position = 10;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator1]));
		w16.Position = 11;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Exzessdarstellung");
		this.vbox4.Add (this.label5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label5]));
		w17.Position = 12;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.zdeexzess = new global::Gtk.Entry ();
		this.zdeexzess.CanFocus = true;
		this.zdeexzess.Name = "zdeexzess";
		this.zdeexzess.IsEditable = true;
		this.zdeexzess.InvisibleChar = '•';
		this.vbox4.Add (this.zdeexzess);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.zdeexzess]));
		w18.Position = 13;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Bias:");
		this.hbox4.Add (this.label6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label6]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.zdebias = new global::Gtk.Entry ();
		this.zdebias.CanFocus = true;
		this.zdebias.Name = "zdebias";
		this.zdebias.IsEditable = true;
		this.zdebias.InvisibleChar = '•';
		this.hbox4.Add (this.zdebias);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.zdebias]));
		w20.Position = 1;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w21.Position = 14;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.zdrbexfrom = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("From"));
		this.zdrbexfrom.CanFocus = true;
		this.zdrbexfrom.Name = "zdrbexfrom";
		this.zdrbexfrom.DrawIndicator = true;
		this.zdrbexfrom.UseUnderline = true;
		this.zdrbexfrom.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox3.Add (this.zdrbexfrom);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.zdrbexfrom]));
		w22.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.zdrbexto = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("To"));
		this.zdrbexto.CanFocus = true;
		this.zdrbexto.Name = "zdrbexto";
		this.zdrbexto.DrawIndicator = true;
		this.zdrbexto.UseUnderline = true;
		this.zdrbexto.Group = this.zdrbexfrom.Group;
		this.hbox3.Add (this.zdrbexto);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.zdrbexto]));
		w23.Position = 1;
		this.vbox4.Add (this.hbox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
		w24.Position = 15;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.rdbexzess = new global::Gtk.Button ();
		this.rdbexzess.CanFocus = true;
		this.rdbexzess.Name = "rdbexzess";
		this.rdbexzess.UseUnderline = true;
		this.rdbexzess.Label = global::Mono.Unix.Catalog.GetString ("Convert...");
		this.vbox4.Add (this.rdbexzess);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rdbexzess]));
		w25.Position = 16;
		w25.Expand = false;
		w25.Fill = false;
		this.hbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.textview1.AcceptsTab = false;
		this.GtkScrolledWindow.Add (this.textview1);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
		w28.Position = 1;
		this.notebook2.Add (this.hbox1);
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Zahlen Repraesentation");
		this.notebook2.SetTabLabel (this.hbox1, this.label4);
		this.label4.ShowAll ();
		// Notebook tab
		global::Gtk.Label w30 = new global::Gtk.Label ();
		w30.Visible = true;
		this.notebook2.Add (w30);
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("KV-Diagramm");
		this.notebook2.SetTabLabel (w30, this.label1);
		this.label1.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("GKZ1");
		this.hbox6.Add (this.label8);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label8]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.GKZ1E = new global::Gtk.Entry ();
		this.GKZ1E.CanFocus = true;
		this.GKZ1E.Name = "GKZ1E";
		this.GKZ1E.Text = global::Mono.Unix.Catalog.GetString ("11000011111010000000000000000000");
		this.GKZ1E.IsEditable = true;
		this.GKZ1E.InvisibleChar = '•';
		this.hbox6.Add (this.GKZ1E);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.GKZ1E]));
		w32.Position = 1;
		this.vbox3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("GKZ2");
		this.hbox7.Add (this.label9);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label9]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.GKZ2E = new global::Gtk.Entry ();
		this.GKZ2E.CanFocus = true;
		this.GKZ2E.Name = "GKZ2E";
		this.GKZ2E.Text = global::Mono.Unix.Catalog.GetString ("11000010110100000000000000000000");
		this.GKZ2E.IsEditable = true;
		this.GKZ2E.InvisibleChar = '•';
		this.hbox7.Add (this.GKZ2E);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.GKZ2E]));
		w35.Position = 1;
		this.vbox3.Add (this.hbox7);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GKZCB = global::Gtk.ComboBoxEntry.NewText ();
		this.GKZCB.AppendText (global::Mono.Unix.Catalog.GetString ("Multiplikation"));
		this.GKZCB.Name = "GKZCB";
		this.GKZCB.Active = 0;
		this.vbox3.Add (this.GKZCB);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GKZCB]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		this.vbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Vorzeichen: ");
		this.hbox8.Add (this.label10);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label10]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.GKZ1Evz = new global::Gtk.Entry ();
		this.GKZ1Evz.CanFocus = true;
		this.GKZ1Evz.Name = "GKZ1Evz";
		this.GKZ1Evz.IsEditable = false;
		this.GKZ1Evz.InvisibleChar = '•';
		this.hbox8.Add (this.GKZ1Evz);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.GKZ1Evz]));
		w40.Position = 1;
		this.vbox6.Add (this.hbox8);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox8]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Exponent:");
		this.hbox10.Add (this.label11);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label11]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.GKZ1Eex = new global::Gtk.Entry ();
		this.GKZ1Eex.CanFocus = true;
		this.GKZ1Eex.Name = "GKZ1Eex";
		this.GKZ1Eex.IsEditable = false;
		this.GKZ1Eex.InvisibleChar = '•';
		this.hbox10.Add (this.GKZ1Eex);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.GKZ1Eex]));
		w43.Position = 1;
		this.vbox6.Add (this.hbox10);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox10]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Mantisse:");
		this.hbox11.Add (this.label12);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label12]));
		w45.Position = 0;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.GKZ1Eman = new global::Gtk.Entry ();
		this.GKZ1Eman.CanFocus = true;
		this.GKZ1Eman.Name = "GKZ1Eman";
		this.GKZ1Eman.IsEditable = false;
		this.GKZ1Eman.InvisibleChar = '•';
		this.hbox11.Add (this.GKZ1Eman);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.GKZ1Eman]));
		w46.Position = 1;
		this.vbox6.Add (this.hbox11);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox11]));
		w47.Position = 2;
		w47.Expand = false;
		w47.Fill = false;
		this.GtkAlignment.Add (this.vbox6);
		this.frame2.Add (this.GtkAlignment);
		this.GtkLabel9 = new global::Gtk.Label ();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GKZ1</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel9;
		this.vbox5.Add (this.frame2);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame2]));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Vorzeichen: ");
		this.hbox9.Add (this.label13);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label13]));
		w51.Position = 0;
		w51.Expand = false;
		w51.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.GKZ2Evz = new global::Gtk.Entry ();
		this.GKZ2Evz.CanFocus = true;
		this.GKZ2Evz.Name = "GKZ2Evz";
		this.GKZ2Evz.IsEditable = false;
		this.GKZ2Evz.InvisibleChar = '•';
		this.hbox9.Add (this.GKZ2Evz);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.GKZ2Evz]));
		w52.Position = 1;
		this.vbox7.Add (this.hbox9);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox9]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Exponent:");
		this.hbox12.Add (this.label14);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label14]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.GKZ2Eex = new global::Gtk.Entry ();
		this.GKZ2Eex.CanFocus = true;
		this.GKZ2Eex.Name = "GKZ2Eex";
		this.GKZ2Eex.IsEditable = false;
		this.GKZ2Eex.InvisibleChar = '•';
		this.hbox12.Add (this.GKZ2Eex);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.GKZ2Eex]));
		w55.Position = 1;
		this.vbox7.Add (this.hbox12);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox12]));
		w56.Position = 1;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Mantisse:");
		this.hbox13.Add (this.label15);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label15]));
		w57.Position = 0;
		w57.Expand = false;
		w57.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.GKZ2Eman = new global::Gtk.Entry ();
		this.GKZ2Eman.CanFocus = true;
		this.GKZ2Eman.Name = "GKZ2Eman";
		this.GKZ2Eman.IsEditable = false;
		this.GKZ2Eman.InvisibleChar = '•';
		this.hbox13.Add (this.GKZ2Eman);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.GKZ2Eman]));
		w58.Position = 1;
		this.vbox7.Add (this.hbox13);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox13]));
		w59.Position = 2;
		w59.Expand = false;
		w59.Fill = false;
		this.GtkAlignment1.Add (this.vbox7);
		this.frame3.Add (this.GtkAlignment1);
		this.GtkLabel10 = new global::Gtk.Label ();
		this.GtkLabel10.Name = "GtkLabel10";
		this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GKZ1</b>");
		this.GtkLabel10.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel10;
		this.vbox5.Add (this.frame3);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame3]));
		w62.Position = 1;
		w62.Expand = false;
		w62.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.GKZEerg = new global::Gtk.Entry ();
		this.GKZEerg.CanFocus = true;
		this.GKZEerg.Name = "GKZEerg";
		this.GKZEerg.IsEditable = true;
		this.GKZEerg.InvisibleChar = '•';
		this.GtkAlignment2.Add (this.GKZEerg);
		this.frame1.Add (this.GtkAlignment2);
		this.GtkLabel12 = new global::Gtk.Label ();
		this.GtkLabel12.Name = "GtkLabel12";
		this.GtkLabel12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ergebnis</b>");
		this.GtkLabel12.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel12;
		this.vbox8.Add (this.frame1);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.frame1]));
		w65.Position = 0;
		w65.Expand = false;
		w65.Fill = false;
		this.vbox5.Add (this.vbox8);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox8]));
		w66.Position = 2;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GKZB = new global::Gtk.Button ();
		this.GKZB.HeightRequest = 85;
		this.GKZB.CanFocus = true;
		this.GKZB.Name = "GKZB";
		this.GKZB.UseUnderline = true;
		this.GKZB.Label = global::Mono.Unix.Catalog.GetString ("Give me an answer...");
		this.vbox5.Add (this.GKZB);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GKZB]));
		w67.Position = 4;
		w67.Expand = false;
		w67.Fill = false;
		this.hbox5.Add (this.vbox5);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox5]));
		w68.Position = 0;
		w68.Expand = false;
		w68.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.GKZTV = new global::Gtk.TextView ();
		this.GKZTV.CanFocus = true;
		this.GKZTV.Name = "GKZTV";
		this.GtkScrolledWindow1.Add (this.GKZTV);
		this.hbox5.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.GtkScrolledWindow1]));
		w70.Position = 1;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w71.Position = 1;
		this.notebook2.Add (this.vbox2);
		global::Gtk.Notebook.NotebookChild w72 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox2]));
		w72.Position = 2;
		// Notebook tab
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Gleitkommaarithmetik");
		this.notebook2.SetTabLabel (this.vbox2, this.label7);
		this.label7.ShowAll ();
		this.vbox1.Add (this.notebook2);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook2]));
		w73.PackType = ((global::Gtk.PackType)(1));
		w73.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 947;
		this.DefaultHeight = 718;
		this.notebook2.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.BeendenAction.Activated += new global::System.EventHandler (this.OnBeendenActionActivated);
		this.zdbconvert.Clicked += new global::System.EventHandler (this.OnZdbconvertClicked);
		this.zdbdarstellung.Clicked += new global::System.EventHandler (this.OnZdbdarstellungClicked);
		this.rdbexzess.Clicked += new global::System.EventHandler (this.OnRdbexzessClicked);
		this.GKZB.Clicked += new global::System.EventHandler (this.OnGKZBClicked);
	}
}
